// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zXu-DJ2ei7dB4GCvoo245UDQVGkBBV8',
    appId: '1:903034389136:web:cdaac1473650cb5aff4e15',
    messagingSenderId: '903034389136',
    projectId: 'easy2cook-4afc5',
    authDomain: 'easy2cook-4afc5.firebaseapp.com',
    storageBucket: 'easy2cook-4afc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxq3ouHIoxupnNyhG8FQjVDBeR-PTldZM',
    appId: '1:903034389136:android:60ddfa5f760714f1ff4e15',
    messagingSenderId: '903034389136',
    projectId: 'easy2cook-4afc5',
    storageBucket: 'easy2cook-4afc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PaO1kH1OEzsPkGqURqhftQEWhVVjg_Y',
    appId: '1:903034389136:ios:f18bdc39dd3eabb3ff4e15',
    messagingSenderId: '903034389136',
    projectId: 'easy2cook-4afc5',
    storageBucket: 'easy2cook-4afc5.appspot.com',
    iosClientId: '903034389136-drui85f7388mii190n5v99sjjv2ikju7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easy2cook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PaO1kH1OEzsPkGqURqhftQEWhVVjg_Y',
    appId: '1:903034389136:ios:f18bdc39dd3eabb3ff4e15',
    messagingSenderId: '903034389136',
    projectId: 'easy2cook-4afc5',
    storageBucket: 'easy2cook-4afc5.appspot.com',
    iosClientId: '903034389136-drui85f7388mii190n5v99sjjv2ikju7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easy2cook',
  );
}
